### ISSUE TITLE
Component formatting.

### ISSUE THREAD

**Issue by farishkash** [NeilMcGlennon/Jammming#1]
https://github.com/NeilMcGlennon/Jammming/blob/5a513d87342b7af2285804f2669dd6a6384f5496/src/components/App/App.js#L85-L90

Just a suggestion here, it is easy to denote the endpoint if you move the closing /> to the next line.  Example below.

```
<Playlist 
   playlistName={this.state.playlistName} 
   playlistTracks={this.state.playlistTracks} 
   onRemove={this.removeTrack} 
   onNameChange={this.updatePlaylistName} 
   onSave={this.savePlaylist}
/> 
```

**Comment by NeilMcGlennon** [comment]
This has now been changed. @farishkash
