### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by farishkash** [NeilMcGlennon/Jammming#3]
Overall met expectations.

This one of the shortest reviews I have done for this project.  The reason being is that you avoided the common mistakes that usually get presented to me for review.

Code formatting is clean and well structured.  Great use of comments to see what is going on with the Spotify section. 

I saw no major flaws or errors.  The project function properly.  I went to my online account and saw the new playlist added.

Good luck with your feature request.

**Comment by NeilMcGlennon** [comment]
Thanks!
